# This is a basic workflow to help you get started with Actions

name: Deploy NRT Scripts to AWS

# Controls when the action will run. Triggers the workflow on push to master
on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4.1.1

    - name: Run SSH command
      uses: appleboy/ssh-action@v1.0.0
      with:
        # Command to execute on the remote server.
        script: sudo /home/ubuntu/scripts/install.sh
        # Hostname or IP address of the server.
        host: ec2-3-80-230-37.compute-1.amazonaws.com
        # Username for authentication.
        username: ubuntu
        # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        key: ${{secrets.EC2_PRIVATE_KEY}}
